### PR TITLE
fix construct and parent call

### PR DESCRIPTION
**Pull request by remicollet**
XML_Parser 1.3.5 switch constructor name, so $this->XML_Parser doesn't work anymore

@cweiske @till I think this one is urgent.

### CODE REVIEW

**Comment by remicollet** [comment]
Notice: with this change, XML_RSS and XML_Parser test suite are ok.

**Comment by till** [comment]
@remicollet this looks good to me. Not entirely sure how we release this? `pear package`?

cc @cweiske @saltybeagle @CloCkWeRX

**Comment by kenguest** [comment]
1.3.6 was released via pear yesterday, so this should be rolled out as 1.3.7 today. ( https://pear.php.net/package/XML_Parser/download/ )

**Comment by remicollet** [comment]
@kenguest ?

This PR is for XML_RSS (so probably 1.1.0, as  raising php min version to 5), why do you say 1.3.7 ?

**Comment by kenguest** [comment]
You mentioned XML_Parser in the comment and 1.3.7 would be the next logical version number for that package. Though of course we are talking about XML_RSS here...

XML_RSS should next be 1.1.0a1 - which I will release later on today if nobody does so before me.

**Comment by kenguest** [comment]
Build and tests on travis are looking good - https://travis-ci.org/pear/XML_RSS/builds/77590720 - so I tagged and rolled out a fresh release: http://pear.php.net/package/XML_RSS/download/

**Pull request merged**
